DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE BAIRRO CASCADE CONSTRAINTS;
DROP TABLE TIPO_DESASTRE CASCADE CONSTRAINTS;
DROP TABLE ENDERECO CASCADE CONSTRAINTS;
DROP TABLE SENSOR CASCADE CONSTRAINTS;
DROP TABLE ALERTA CASCADE CONSTRAINTS;
DROP TABLE POSTAGEM CASCADE CONSTRAINTS;
DROP TABLE COMENTARIO CASCADE CONSTRAINTS;
DROP TABLE CONFIRMA_POSTAGEM CASCADE CONSTRAINTS;

-- 2 Criação das Tabelas com Restrições – 10 pontos

CREATE TABLE USUARIO (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_usuario VARCHAR(100) NOT NULL,
    email_usuario VARCHAR(200) NOT NULL UNIQUE,
    senha_usuario VARCHAR(50) NOT NULL,
    telefone_usuario VARCHAR(11) NOT NULL UNIQUE,
    tipo_usuario VARCHAR(50) DEFAULT 'Usuário' NOT NULL,
    CONSTRAINT chk_tipo_usuario CHECK (tipo_usuario IN ('Usuário', 'Funcionário'))
);

CREATE TABLE BAIRRO (
    id_bairro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_bairro VARCHAR(100) NOT NULL UNIQUE,
    zona_bairro VARCHAR(50),
    CONSTRAINT chk_zona_bairro CHECK (zona_bairro IN ('Zona Sul', 'Zona Norte', 'Zona Leste', 'Zona Oeste', 'Zona Central'))
);

CREATE TABLE TIPO_DESASTRE (
    id_desastre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_desastre VARCHAR(100) NOT NULL,
    CONSTRAINT chk_nome_desastre CHECK (nome_desastre IN ('Enchente', 'Inundação', 'Deslizamento', 'Queimada', 'Incêndio Florestal', 'Tempestade', 'Vendaval')),
    descricao_desastre VARCHAR(255) NOT NULL
);

CREATE TABLE ENDERECO (
    id_endereco NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logradouro_endereco VARCHAR(255),
    numero_endereco VARCHAR(10),
    complemento_endereco VARCHAR(255),
    cep_endereco VARCHAR(9),
    bairro_id_bairro NUMBER NOT NULL,
    CONSTRAINT endereco_bairro_fk FOREIGN KEY (bairro_id_bairro) REFERENCES BAIRRO(id_bairro) ON DELETE CASCADE
);

CREATE TABLE SENSOR (
    id_sensor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_sensor VARCHAR(100) NOT NULL,
    tipo_sensor VARCHAR(50) NOT NULL,
    bairro_id_bairro NUMBER,
    CONSTRAINT sensor_bairro_fk FOREIGN KEY (bairro_id_bairro) REFERENCES BAIRRO(id_bairro)
);

CREATE TABLE ALERTA (
    id_alerta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nivel_risco VARCHAR(50) NOT NULL,
    CONSTRAINT chk_nivel_risco CHECK (nivel_risco IN ('Atenção', 'Alerta', 'Emergência')),
    data_alerta DATE NOT NULL,
    descricao_alerta VARCHAR(255),
    status_alerta VARCHAR(50) DEFAULT 'Ativo' NOT NULL,
    CONSTRAINT chk_status_alerta CHECK (status_alerta IN ('Ativo', 'Resolvido')),
    sensor_id_sensor NUMBER NOT NULL,
    tipo_desastre_id_desastre NUMBER NOT NULL,
    CONSTRAINT alerta_sensor_fk FOREIGN KEY (sensor_id_sensor) REFERENCES SENSOR(id_sensor) ON DELETE CASCADE,
    CONSTRAINT alerta_tipo_desastre_fk FOREIGN KEY (tipo_desastre_id_desastre) REFERENCES TIPO_DESASTRE(id_desastre) ON DELETE CASCADE
);

CREATE TABLE POSTAGEM (
    id_postagem NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo_postagem VARCHAR(100) NOT NULL,
    descricao_postagem VARCHAR(255) NOT NULL,
    data_postagem DATE NOT NULL,
    tipo_postagem VARCHAR(50) DEFAULT 'Usuário' NOT NULL,
    CONSTRAINT chk_tipo_postagem CHECK (tipo_postagem IN ('Usuário', 'Governo')),
    status_postagem VARCHAR(50) DEFAULT 'Ativo' NOT NULL,
    CONSTRAINT chk_status_postagem CHECK (status_postagem IN ('Ativo', 'Resolvido', 'Descartado')),
    usuario_id_usuario NUMBER,
    endereco_id_endereco NUMBER,
    tipo_desastre_id_desastre NUMBER,
    CONSTRAINT postagem_usuario_fk FOREIGN KEY (usuario_id_usuario) REFERENCES USUARIO(id_usuario),
    CONSTRAINT postagem_endereco_fk FOREIGN KEY (endereco_id_endereco) REFERENCES ENDERECO(id_endereco) ON DELETE CASCADE,
    CONSTRAINT postagem_tipo_desastre_fk FOREIGN KEY (tipo_desastre_id_desastre) REFERENCES TIPO_DESASTRE(id_desastre) ON DELETE CASCADE 
);

CREATE TABLE COMENTARIO (
    id_comentario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto_comentario VARCHAR(255) NOT NULL,
    data_comentario DATE NOT NULL,
    postagem_id_postagem NUMBER,
    usuario_id_usuario NUMBER,
    CONSTRAINT comentario_usuario_fk FOREIGN KEY (usuario_id_usuario) REFERENCES USUARIO(id_usuario),
    CONSTRAINT comentario_postagem_fk FOREIGN KEY (postagem_id_postagem) REFERENCES POSTAGEM(id_postagem) ON DELETE CASCADE
);

CREATE TABLE CONFIRMA_POSTAGEM (
    id_usuario NUMBER NOT NULL,
    id_postagem NUMBER NOT NULL,
    data_confirma DATE NOT NULL,
    PRIMARY KEY (id_usuario, id_postagem),
    CONSTRAINT confirma_postagem_usuario_fk FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario) ON DELETE CASCADE,
    CONSTRAINT confirma_postagem_postagem_fk FOREIGN KEY (id_postagem) REFERENCES POSTAGEM(id_postagem) ON DELETE CASCADE
);

-- 3 Procedures DML por Tabela (Apenas INSERT, UPDATE e DELETE) – 25 pontos

-- INSERTS USUARIO
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario, tipo_usuario) VALUES ('Ana Souza', 'ana.souza@gmail.com', 'admin', '11912345678', 'Funcionário');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Bruno Lima', 'bruno.lima@gmail.com', 'senha123', '11923456789');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Carla Mendes', 'carla.mendes@gmail.com', 'senha123', '11934567890');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Daniel Alves', 'daniel.alves@gmail.com', 'senha123', '11945678901');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Eduarda Silva', 'eduarda.silva@gmail.com', 'senha123', '11956789012');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Felipe Costa', 'felipe.costa@gmail.com', 'senha123', '11967890123');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Gabriela Rocha', 'gabriela.rocha@gmail.com', 'senha123', '11978901234');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Henrique Dias', 'henrique.dias@gmail.com', 'senha123', '11989012345');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Isabela Faria', 'isabela.faria@gmail.com', 'senha123', '11900123456');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('João Pedro', 'joao.pedro@gmail.com', 'senha123', '11911234567');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Kátia Moraes', 'katia.moraes@gmail.com', 'senha123', '11922345678');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Lucas Martins', 'lucas.martins@gmail.com', 'senha123', '11933456789');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Mariana Nunes', 'mariana.nunes@gmail.com', 'senha123', '11944567890');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Natália Reis', 'natalia.reis@gmail.com', 'senha123', '11955678901');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Otávio Cunha', 'otavio.cunha@gmail.com', 'senha123', '11966789012');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Patrícia Lopes', 'patricia.lopes@gmail.com', 'senha123', '11977890123');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Rafael Torres', 'rafael.torres@gmail.com', 'senha123', '11988901234');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Sara Menezes', 'sara.menezes@gmail.com', 'senha123', '11999012345');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Thiago Ramos', 'thiago.ramos@gmail.com', 'senha123', '11910123456');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Úrsula Dantas', 'ursula.dantas@gmail.com', 'senha123', '11921234567');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Vinícius Prado', 'vinicius.prado@gmail.com', 'senha123', '11932345678');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Wesley Monteiro', 'wesley.monteiro@gmail.com', 'senha123', '11943456789');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Ximena Vargas', 'ximena.vargas@gmail.com', 'senha123', '11954567890');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Yasmin Queiroz', 'yasmin.queiroz@gmail.com', 'senha123', '11965678901');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Zeca Barros', 'zeca.barros@gmail.com', 'senha123', '11976789012');
    INSERT INTO USUARIO (nome_usuario, email_usuario, senha_usuario, telefone_usuario) VALUES ('Roberto Silva', 'roberto.silva@gmail.com', 'senha123', '11928393847');
    
-- UPDATE E DELETE USUARIO
    UPDATE USUARIO SET nome_usuario = 'Alberto Gomes', email_usuario = 'alberto.gomes@gmail.com', senha_usuario = 'alberto123', telefone_usuario = '11938274635' WHERE id_usuario = 26;
    DELETE FROM USUARIO WHERE id_usuario = 26;

-- INSERTS BAIRRO
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Santo Amaro', 'Zona Sul');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Capão Redondo', 'Zona Sul');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Campo Limpo', 'Zona Sul');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Vila Mariana', 'Zona Sul');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Jabaquara', 'Zona Sul');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Santana', 'Zona Norte');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Tucuruvi', 'Zona Norte');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Casa Verde', 'Zona Norte');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Vila Maria', 'Zona Norte');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Freguesia do Ó', 'Zona Norte');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Tatuapé', 'Zona Leste');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Itaquera', 'Zona Leste');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('São Miguel Paulista', 'Zona Leste');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Penha', 'Zona Leste');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Mooca', 'Zona Leste');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Lapa', 'Zona Oeste');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Pinheiros', 'Zona Oeste');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Perdizes', 'Zona Oeste');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Butantã', 'Zona Oeste');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Jaguaré', 'Zona Oeste');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Sé', 'Zona Central');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Bela Vista', 'Zona Central');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('República', 'Zona Central');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Consolação', 'Zona Central');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Liberdade', 'Zona Central');
    INSERT INTO BAIRRO (nome_bairro, zona_bairro) VALUES ('Cambuci', 'Zona Sul');
    
-- UPDATE E DELETE BAIRRO    
    UPDATE BAIRRO SET nome_bairro = 'Raposo Tavares', zona_bairro = 'Zona Oeste' WHERE id_bairro = 26;
    DELETE FROM BAIRRO WHERE id_bairro = 26;

-- INSERTS TIPO_DESASTRE
    INSERT INTO TIPO_DESASTRE (nome_desastre, descricao_desastre) VALUES ('Enchente', 'Acúmulo de água causado por excesso de chuvas que eleva o nível dos rios e invade áreas urbanas.');
    INSERT INTO TIPO_DESASTRE (nome_desastre, descricao_desastre) VALUES ('Inundação', 'Alagamento rápido de áreas devido ao transbordamento de rios ou acúmulo de água em áreas urbanas.');
    INSERT INTO TIPO_DESASTRE (nome_desastre, descricao_desastre) VALUES ('Deslizamento', 'Deslocamento de massas de terra ou rochas em encostas, geralmente causado por chuvas intensas.');
    INSERT INTO TIPO_DESASTRE (nome_desastre, descricao_desastre) VALUES ('Queimada', 'Fogo descontrolado em vegetação rasteira ou campos, muitas vezes de origem humana.');
    INSERT INTO TIPO_DESASTRE (nome_desastre, descricao_desastre) VALUES ('Incêndio Florestal', 'Fogo de grandes proporções que se espalha por matas e florestas, podendo afetar fauna, flora e pessoas.');
    INSERT INTO TIPO_DESASTRE (nome_desastre, descricao_desastre) VALUES ('Tempestade', 'Fenômeno climático com ventos fortes, chuvas intensas, raios e trovões.');
    INSERT INTO TIPO_DESASTRE (nome_desastre, descricao_desastre) VALUES ('Vendaval', 'Ventos muito fortes e repentinos que podem causar quedas de árvores, destelhamentos e danos a estruturas.');
    INSERT INTO TIPO_DESASTRE (nome_desastre, descricao_desastre) VALUES ('Vendaval', 'Ventos extremamente fortes');
    
-- UPDATE E DELETE TIPO_DESASTRE
    UPDATE TIPO_DESASTRE SET nome_desastre = 'Enchente', descricao_desastre = 'Atualizado' WHERE id_desastre = 8;
    DELETE FROM TIPO_DESASTRE WHERE id_desastre = 8;

-- INSERTS ENDERECO
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Av. João Dias', '1000', 'Próximo ao metrô', '04724-003', 1);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Rua Serra Dourada', '345', NULL, '04929-000', 2);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Av. Carlos Caldeira Filho', '800', 'Apto 12', '05802-140', 3);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Rua Domingos de Morais', '1250', 'Bloco B', '04010-001', 4);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Av. Eng. George Corbisier', '567', NULL, '04345-000', 5);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Rua Dr. Zuquim', '678', NULL, '02035-040', 6);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Av. Mazzei', '232', 'Fundos', '02310-002', 7);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Rua Bernardino Fanganiello', '99', NULL, '02521-060', 8);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Av. Guilherme Cotching', '410', NULL, '02115-000', 9);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Av. Itaberaba', '5600', 'Casa 1', '02739-000', 10);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Rua Antonio de Barros', '1234', NULL, '03401-000', 11);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Av. Itaquera', '8888', NULL, '08295-000', 12);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Rua Maria Luiza Americano', '256', 'Térreo', '08010-000', 13);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Rua Padre Benedito de Camargo', '77', NULL, '03628-000', 14);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Rua da Mooca', '500', 'Sala 3', '03166-000', 15);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Rua Pio XI', '789', NULL, '05060-001', 16);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Rua dos Pinheiros', '1420', 'Apto 34', '05422-002', 17);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Rua Turiassu', '299', NULL, '05005-000', 18);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Av. Vital Brasil', '1120', NULL, '05503-000', 19);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Av. Jaguaré', '2012', NULL, '05346-000', 20);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Praça da Sé', '1', 'Centro Histórico', '01001-000', 21);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Rua Santo Amaro', '350', NULL, '01315-001', 22);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Av. Ipiranga', '200', NULL, '01046-925', 23);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Rua da Consolação', '987', NULL, '01301-000', 24);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Rua Galvão Bueno', '400', NULL, '01506-000', 25);
  INSERT INTO ENDERECO (logradouro_endereco, numero_endereco, complemento_endereco, cep_endereco, bairro_id_bairro) VALUES ('Rua Galvão Bueno', '404', NULL, '01506-000', 25);

-- UPDATE E DELETE ENDERECO
  UPDATE ENDERECO SET logradouro_endereco = 'Rua dos Pinheiros', numero_endereco = '1320', complemento_endereco = 'Perto da Praça', cep_endereco = '05422-002', bairro_id_bairro = 17 WHERE id_endereco = 26;
  DELETE FROM ENDERECO WHERE id_endereco = 26;

-- INSERTS SENSOR
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-01', 'Sensor de Enchente', 1);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-02', 'Sensor de Enchente', 2);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-03', 'Sensor de Inundação', 3);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-04', 'Sensor de Vendaval', 4);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-05', 'Sensor de Enchente', 5);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-06', 'Sensor de Inundação', 6);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-07', 'Sensor de Enchente', 7);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-08', 'Sensor de Deslizamento de Terra', 8);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-09', 'Sensor de Enchente', 9);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-10', 'Sensor de Queimada', 10);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-11', 'Sensor de Enchente', 11);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-12', 'Sensor de Tempestade', 12);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-13', 'Sensor de Deslizamento de Terra', 13);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-14', 'Sensor de Inundação', 14);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-15', 'Sensor de Enchente', 15);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-16', 'Sensor de Enchente', 16);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-17', 'Sensor de Deslizamento de Terra', 17);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-18', 'Sensor de Inundação', 18);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-19', 'Sensor de Vendaval', 19);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-20', 'Sensor de Tempestade', 20);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-21', 'Sensor de Enchente', 21);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-22', 'Sensor de Queimada', 22);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-23', 'Sensor de Enchente', 23);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-24', 'Sensor de Enchente', 24);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-25', 'Sensor de Vendaval', 25);
    INSERT INTO SENSOR (nome_sensor, tipo_sensor, bairro_id_bairro) VALUES ('S-26', 'Sensor de Enchente', 25);
    
-- UPDATE E DELETE SENSOR
    UPDATE SENSOR SET nome_sensor = 'SO-26', tipo_sensor = 'Sensor de Tempestade', bairro_id_bairro = 21 WHERE id_sensor = 26;
    DELETE FROM SENSOR WHERE id_sensor = 26;
    
-- INSERTS ALERTA
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Atenção', SYSDATE, 'Detectada possível enchente no bairro de Santo Amaro, na Zona Sul de São Paulo.', 'Ativo', 1, 1);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Atenção', SYSDATE, 'Detectada possível enchente no bairro do Capão Redondo, na Zona Sul de São Paulo', 'Ativo', 2, 1);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Atenção', SYSDATE, 'Detectada possível inundação no bairro de Campo Limpo, na Zona Sul de São Paulo.', 'Ativo', 3, 2);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Alerta', SYSDATE, 'Risco de vendaval identificado no bairro de Vila Mariana, na Zona Sul de São Paulo.', 'Ativo', 4, 4);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Atenção', SYSDATE, 'Sensor detectou elevação do nível da água no bairro de Jabaquara, Zona Sul.', 'Ativo', 5, 1);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Alerta', SYSDATE, 'Inundação em estágio inicial detectada no bairro de Santana, Zona Norte de São Paulo.', 'Ativo', 6, 2);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Atenção', SYSDATE, 'Sensor registra acúmulo de água no bairro de Tucuruvi, Zona Norte.', 'Ativo', 7, 1);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Emergência', SYSDATE, 'Alto risco de deslizamento de terra no bairro de Casa Verde, Zona Norte.', 'Ativo', 8, 3);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Atenção', SYSDATE, 'Sensor registra nível anormal de água no bairro de Vila Maria, Zona Norte.', 'Ativo', 9, 1);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Alerta', SYSDATE, 'Possível foco de queimada detectado no bairro de Freguesia do Ó, Zona Norte.', 'Ativo', 10, 5);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Atenção', SYSDATE, 'Nível de água elevado no bairro de Tatuapé, Zona Leste.', 'Ativo', 11, 1);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Alerta', SYSDATE, 'Tempestade em aproximação identificada no bairro de Itaquera, Zona Leste.', 'Ativo', 12, 6);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Emergência', SYSDATE, 'Risco elevado de deslizamento no bairro de São Miguel Paulista, Zona Leste.', 'Ativo', 13, 3);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Alerta', SYSDATE, 'Inundação iminente no bairro da Penha, Zona Leste.', 'Ativo', 14, 2);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Atenção', SYSDATE, 'Sensor indica possível enchente no bairro da Mooca, Zona Leste.', 'Ativo', 15, 1);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Atenção', SYSDATE, 'Possível enchente no bairro da Lapa, Zona Oeste de São Paulo.', 'Ativo', 16, 1);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Emergência', SYSDATE, 'Risco alto de deslizamento de terra no bairro de Pinheiros, Zona Oeste.', 'Ativo', 17, 3);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Alerta', SYSDATE, 'Inundação identificada no bairro de Perdizes, Zona Oeste.', 'Ativo', 18, 2);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Alerta', SYSDATE, 'Risco de ventos fortes detectado no bairro de Butantã, Zona Oeste.', 'Ativo', 19, 4);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Alerta', SYSDATE, 'Tempestade detectada na região do Jaguaré, Zona Oeste.', 'Ativo', 20, 6);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Atenção', SYSDATE, 'Sensor registra elevação de água no bairro da Sé, Zona Central.', 'Ativo', 21, 1);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Alerta', SYSDATE, 'Foco de queimada identificado no bairro da Bela Vista, Zona Central.', 'Ativo', 22, 5);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Atenção', SYSDATE, 'Enchente sendo monitorada no bairro da República, Zona Central.', 'Ativo', 23, 1);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Atenção', SYSDATE, 'Sensor indica enchente em desenvolvimento no bairro da Consolação, Zona Central.', 'Ativo', 24, 1);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Alerta', SYSDATE, 'Possibilidade de vendaval no bairro da Liberdade, Zona Central.', 'Ativo', 25, 4);
    INSERT INTO ALERTA (nivel_risco, data_alerta, descricao_alerta, status_alerta, sensor_id_sensor, tipo_desastre_id_desastre) VALUES ('Emergência', SYSDATE, 'Risco alto de vendaval no bairro da Liberdade, Zona Central.', 'Resolvido', 25, 4);
    
-- UPDATE E DELETE ALERTA

    UPDATE ALERTA SET nivel_risco = 'Atenção', data_alerta = SYSDATE, descricao_alerta = 'Pequena chance de vendaval na região do bairro do Butantã', status_alerta = 'Ativo', sensor_id_sensor = 19, tipo_desastre_id_desastre = 4 WHERE id_alerta = 26; 
    DELETE FROM ALERTA WHERE id_alerta = 26;
    
-- INSERTS POSTAGEM

    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Enchente no centro', 'As ruas próximas à Praça da Sé estão totalmente alagadas.', SYSDATE, 'Governo', 'Ativo', 1, 20, 1);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Deslizamento de terra', 'Houve deslizamento no bairro da Penha após chuvas intensas.', TO_DATE('2025-05-16','YYYY-MM-DD'), 'Usuário', 'Resolvido', 2, 14, 3);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Alagamento em Santo Amaro', 'Toda a Rua Santo Amaro está intransitável.', SYSDATE, 'Usuário', 'Ativo', 4, 21, 2);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Vento forte derruba árvores', 'Ventos fortes causaram quedas de árvores na Av. Mazzei.', SYSDATE, 'Governo', 'Ativo', 1, 7, 7);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Incêndio em prédio', 'Incêndio florestal se alastrou e atingiu casas próximas.', SYSDATE, 'Usuário', 'Ativo', 6, 15, 5);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Tempestade forte', 'Tempestade com raios atingiu fiação na Mooca.', TO_DATE('2025-05-21','YYYY-MM-DD'), 'Governo', 'Resolvido', 1, 14, 6);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Inundação rápida', 'Transbordamento de rio causou alagamento em Pirituba.', TO_DATE('2025-05-26','YYYY-MM-DD'), 'Usuário', 'Descartado', 9, 10, 2);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Risco de deslizamento', 'Moradores relatam rachaduras em encosta.', SYSDATE, 'Governo', 'Ativo', 1, 13, 3);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Fumaça intensa', 'Queimada afeta visibilidade na região da Lapa.', SYSDATE, 'Usuário', 'Ativo', 2, 16, 4);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Temporais recorrentes', 'Choveu 3 dias seguidos, risco de inundação.', TO_DATE('2025-05-27','YYYY-MM-DD'), 'Governo', 'Resolvido', 1, 5, 6);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Rua interditada', 'Rua fechada após início de alagamento em Itaberaba.', SYSDATE, 'Usuário', 'Ativo', 4, 10, 2);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Poste caído', 'Vendaval causou queda de poste na zona norte.', SYSDATE, 'Usuário', 'Ativo', 5, 6, 7);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Fogo se espalha', 'Incêndio florestal se aproxima de casas.', SYSDATE, 'Governo', 'Ativo', 6, 19, 5);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Deslizamento leve', 'Pequeno deslizamento em área de risco.', SYSDATE, 'Usuário', 'Ativo', 7, 17, 3);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Alagamento constante', 'Toda vez que chove, a rua inunda.', SYSDATE, 'Usuário', 'Ativo', 8, 11, 1);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Vento derruba estrutura', 'Cobertura de ponto de ônibus caiu.', TO_DATE('2025-05-27','YYYY-MM-DD'), 'Usuário', 'Resolvido', 10, 8, 7);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Enchente no metrô', 'Estação próxima à Av. João Dias alagada.', SYSDATE, 'Governo', 'Ativo', 1, 1, 1);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Vendaval atinge escola', 'Danos em telhado de escola pública.', TO_DATE('2025-05-29','YYYY-MM-DD'), 'Governo', 'Resolvido', 1, 24, 7);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Tempestade com granizo', 'Granizo danificou veículos na Av. Ipiranga.', SYSDATE, 'Usuário', 'Ativo', 5, 22, 6);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Inundação em bairro central', 'Água invadiu casas e lojas.', SYSDATE, 'Governo', 'Ativo', 1, 9, 2);
    INSERT INTO POSTAGEM (titulo_postagem, descricao_postagem, data_postagem, tipo_postagem, status_postagem, usuario_id_usuario, endereco_id_endereco, tipo_desastre_id_desastre) VALUES ('Vendaval no centro de São Paulo', 'As ruas próximas à Praça da Sé estão totalmente alagadas, com algumas árvores caídas.', SYSDATE, 'Usuário', 'Ativo', 2, 20, 7);

-- UPDATE E DELETE POSTAGEM
    UPDATE POSTAGEM SET titulo_postagem = 'Risco de Deslizamento', descricao_postagem = 'Deslizamento avistado na região do Jaguaré agora mesmo', data_postagem = SYSDATE, tipo_postagem = 'Usuário', usuario_id_usuario = 5, endereco_id_endereco = 19, tipo_desastre_id_desastre = 3 WHERE id_postagem = 21;
    DELETE FROM POSTAGEM WHERE id_postagem = 21;
    
-- INSERTS COMENTARIO

    INSERT INTO COMENTARIO (texto_comentario, data_comentario, postagem_id_postagem, usuario_id_usuario) VALUES ('Situação preocupante, espero que as autoridades ajam rápido.', SYSDATE, 1, 2);
    INSERT INTO COMENTARIO (texto_comentario, data_comentario, postagem_id_postagem, usuario_id_usuario) VALUES ('Essa área sempre sofre com isso, deveriam reforçar a contenção.', TO_DATE('2025-05-17','YYYY-MM-DD'), 2, 3);
    INSERT INTO COMENTARIO (texto_comentario, data_comentario, postagem_id_postagem, usuario_id_usuario) VALUES ('Tem muitos moradores ilhados, alguém precisa ajudar.', SYSDATE, 3, 4);
    INSERT INTO COMENTARIO (texto_comentario, data_comentario, postagem_id_postagem, usuario_id_usuario) VALUES ('Eu vi as árvores caídas, foi assustador.', TO_DATE('2025-05-26','YYYY-MM-DD'), 4, 5);
    INSERT INTO COMENTARIO (texto_comentario, data_comentario, postagem_id_postagem, usuario_id_usuario) VALUES ('O incêndio já foi controlado?', SYSDATE, 5, 6);
    INSERT INTO COMENTARIO (texto_comentario, data_comentario, postagem_id_postagem, usuario_id_usuario) VALUES ('Os bombeiros chegaram rápido nessa ocorrência.', SYSDATE, 13, 2);
    INSERT INTO COMENTARIO (texto_comentario, data_comentario, postagem_id_postagem, usuario_id_usuario) VALUES ('Minha casa foi afetada também, já registrei no app.', SYSDATE, 20, 8);
    INSERT INTO COMENTARIO (texto_comentario, data_comentario, postagem_id_postagem, usuario_id_usuario) VALUES ('Com granizo assim, deviam avisar antes com mais clareza.', TO_DATE('2025-05-27','YYYY-MM-DD'), 19, 9);
    INSERT INTO COMENTARIO (texto_comentario, data_comentario, postagem_id_postagem, usuario_id_usuario) VALUES ('Esse ponto é conhecido por alagar sempre.', SYSDATE, 1, 10);
    INSERT INTO COMENTARIO (texto_comentario, data_comentario, postagem_id_postagem, usuario_id_usuario) VALUES ('O mesmo problema aconteceu no ano passado.', TO_DATE('2025-05-25','YYYY-MM-DD'), 14, 7);
    INSERT INTO COMENTARIO (texto_comentario, data_comentario, postagem_id_postagem, usuario_id_usuario) VALUES ('O mesmo problema aconteceu no ano passado. Essa rua tem esse problema desde que comecei a morar aqui.', SYSDATE, 3, 15);
    
    UPDATE COMENTARIO SET texto_comentario = 'O mesmo problema aconteceu ontem.' WHERE id_comentario = 11;
    DELETE FROM COMENTARIO WHERE id_comentario = 11;

-- INSERTS CONFIRMA_POSTAGEM
    
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (1, 1, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (2, 1, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (3, 2, TO_DATE('2025-05-17','YYYY-MM-DD'));
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (4, 3, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (5, 4, TO_DATE('2025-05-24','YYYY-MM-DD'));
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (6, 5, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (7, 6, TO_DATE('2025-05-21','YYYY-MM-DD'));
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (8, 7, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (9, 8, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (10, 9, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (1, 10, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (2, 11, TO_DATE('2025-05-27','YYYY-MM-DD'));
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (3, 12, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (4, 13, TO_DATE('2025-05-26','YYYY-MM-DD'));
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (5, 14, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (6, 15, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (7, 16, TO_DATE('2025-05-25','YYYY-MM-DD'));
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (8, 17, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (9, 18, TO_DATE('2025-05-29','YYYY-MM-DD'));
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (10, 19, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (1, 2, TO_DATE('2025-05-18','YYYY-MM-DD'));
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (2, 3, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (3, 4, TO_DATE('2025-05-19','YYYY-MM-DD'));
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (4, 5, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (5, 6, TO_DATE('2025-05-20','YYYY-MM-DD'));
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (6, 7, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (7, 8, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (8, 9, TO_DATE('2025-05-22','YYYY-MM-DD'));
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (9, 2, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (10, 11, TO_DATE('2025-05-23','YYYY-MM-DD'));
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (1, 12, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (2, 13, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (3, 14, TO_DATE('2025-05-24','YYYY-MM-DD'));
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (4, 15, SYSDATE);
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (5, 16, TO_DATE('2025-05-25','YYYY-MM-DD'));
    INSERT INTO CONFIRMA_POSTAGEM (id_usuario, id_postagem, data_confirma) VALUES (6, 20, TO_DATE('2025-05-27','YYYY-MM-DD'));
    
    UPDATE CONFIRMA_POSTAGEM SET data_confirma = SYSDATE WHERE id_usuario = 6 AND id_postagem = 20;
    DELETE FROM CONFIRMA_POSTAGEM WHERE id_usuario = 6 AND id_postagem = 20;
    
commit;

-- 4 Funções para Retorno de Dados Processados – 10 pontos

-- Primeira função: retorna o total de confirmações de uma postagem
CREATE OR REPLACE FUNCTION total_confirmacoes_postagem(p_id_postagem NUMBER)
RETURN NUMBER IS
    total_confirmacoes NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO total_confirmacoes
    FROM CONFIRMA_POSTAGEM
    WHERE id_postagem = p_id_postagem;
    
    RETURN total_confirmacoes;
END;

SELECT total_confirmacoes_postagem(2) FROM dual;

-- Segunda função: retorna a média de confirmações por postagem 
CREATE OR REPLACE FUNCTION media_confirmacoes_por_postagem
RETURN NUMBER IS
    v_media NUMBER;
BEGIN
    SELECT AVG(qtd) INTO v_media
    FROM (
        SELECT COUNT(*) AS qtd
        FROM CONFIRMA_POSTAGEM
        GROUP BY id_postagem
    );
    RETURN v_media;
END;

SELECT media_confirmacoes_por_postagem() FROM dual;

set serveroutput on;
set verify off;

-- 5 Blocos Anônimos com Consultas Complexas – 10 pontos

-- Bloco 1: total de postagens por zona em São Paulo
BEGIN
    DBMS_OUTPUT.PUT_LINE('*-* Total de Postagens por Zona *-*');

    FOR registro IN (
        SELECT b.zona_bairro, COUNT(p.id_postagem) AS total_postagens
        FROM POSTAGEM p
        JOIN ENDERECO e ON p.endereco_id_endereco = e.id_endereco
        JOIN BAIRRO b ON e.bairro_id_bairro = b.id_bairro
        GROUP BY b.zona_bairro
        HAVING COUNT(p.id_postagem) > 0
        ORDER BY total_postagens DESC
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('Zona: ' || registro.zona_bairro || ' | Total de Postagens: ' || registro.total_postagens);
    END LOOP;
END;

-- Bloco 2: quantidade de sensores de tipos específicos por Zona
BEGIN
    FOR registro IN (
        SELECT s.tipo_sensor, b.zona_bairro, COUNT(s.id_sensor) AS total
        FROM SENSOR s
        JOIN BAIRRO b ON s.bairro_id_bairro = b.id_bairro
        GROUP BY s.tipo_sensor, b.zona_bairro
        ORDER BY b.zona_bairro, total DESC
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(registro.zona_bairro || ' | Tipo de Sensor: ' || registro.tipo_sensor || ' | Total: ' || registro.total);
    END LOOP;
END;

-- 6 Cursores Explícitos – 10 pontos

-- Cursor 1: Listando sensores com seus respectivos bairros.
DECLARE
    CURSOR c_sensor IS SELECT s.nome_sensor, b.nome_bairro
    FROM SENSOR s
    JOIN BAIRRO b ON s.bairro_id_bairro = b.id_bairro;
    v_sensor SENSOR.nome_sensor%TYPE;
    v_bairro BAIRRO.nome_bairro%TYPE;
BEGIN
    OPEN c_sensor;
    DBMS_OUTPUT.PUT_LINE('*-* Listagem dos Sensores e seus respectivos Bairros *-*');
    LOOP
        FETCH c_sensor INTO v_sensor, v_bairro;
        EXIT WHEN c_sensor%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE('Sensor: ' || v_sensor || ' | Bairro: ' || v_bairro);
    END LOOP;
    CLOSE c_sensor;
END;

-- Cursor 2: Postagens juntamente com a quantidade de confirmações 
DECLARE
    CURSOR c_postagem IS SELECT id_postagem, titulo_postagem FROM POSTAGEM;
    v_id_postagem POSTAGEM.id_postagem%TYPE;
    v_titulo_postagem POSTAGEM.titulo_postagem%TYPE;
    v_total_confirma NUMBER;
BEGIN
    OPEN c_postagem;
    LOOP
        FETCH c_postagem INTO v_id_postagem, v_titulo_postagem;
        EXIT WHEN c_postagem%NOTFOUND;
        SELECT COUNT(*) INTO v_total_confirma FROM CONFIRMA_POSTAGEM WHERE id_postagem = v_id_postagem;
        DBMS_OUTPUT.PUT_LINE('Postagem: ' || v_titulo_postagem || ' | Confirmada por ' || v_total_confirma || ' usuários.');
    END LOOP;
    CLOSE c_postagem;
END;

-- 7 Consultas SQL Complexas (relatórios) – 10 pontos

-- Primeiro Relatório: total de postagens por tipo de desastre
SELECT td.nome_desastre, COUNT(p.id_postagem) AS total_postagens
FROM POSTAGEM p
JOIN TIPO_DESASTRE td ON p.tipo_desastre_id_desastre = td.id_desastre
GROUP BY td.nome_desastre
ORDER BY total_postagens DESC;

-- Segundo Relatório: total de sensores por bairro
SELECT b.nome_bairro, COUNT(s.id_sensor) AS total_sensores
FROM BAIRRO b
LEFT JOIN SENSOR s ON b.id_bairro = s.bairro_id_bairro
GROUP BY b.nome_bairro
ORDER BY total_sensores DESC;

-- Terceiro Relatório: postagens com mais confirmações que a média
SELECT p.titulo_postagem, COUNT(cp.id_usuario) AS total_confirmacoes
FROM POSTAGEM p
JOIN CONFIRMA_POSTAGEM cp ON p.id_postagem = cp.id_postagem
GROUP BY p.titulo_postagem
HAVING COUNT(cp.id_usuario) > (
            SELECT AVG(confirmacoes) 
            FROM (
            SELECT COUNT(*) AS confirmacoes
            FROM CONFIRMA_POSTAGEM
            GROUP BY id_postagem
        )
    )
ORDER BY 
    total_confirmacoes DESC;

-- Quarto Relatório: quantidade de alertas por zona    
SELECT b.zona_bairro, COUNT(a.id_alerta) AS total_alertas
FROM ALERTA a
JOIN SENSOR s ON a.sensor_id_sensor = s.id_sensor
JOIN BAIRRO b ON s.bairro_id_bairro = b.id_bairro
GROUP BY b.zona_bairro
HAVING COUNT(a.id_alerta) > 0
ORDER BY total_alertas DESC;

-- Quinto Relatório: quantidade de alertas por tipo de desastre e status
SELECT td.nome_desastre, a.status_alerta, COUNT(*) AS total_alertas
FROM ALERTA a
JOIN TIPO_DESASTRE td ON a.tipo_desastre_id_desastre = td.id_desastre
GROUP BY td.nome_desastre, a.status_alerta
ORDER BY td.nome_desastre, total_alertas DESC;





